# Generated by Django 5.2.1 on 2025-05-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='tsne_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='tsne_y',
            field=models.FloatField(null=True),
        ),
    ]
